export interface Question {
  id: bigint;
  en: string;
  hi: string;
  mr: string;
  type: "yesno" | "choice" | "scale";
  options?: { value: string; en: string; hi: string; mr: string }[];
  nextMap?: Record<string, bigint>;
  branch?: string;
}

export const QUESTIONS: Question[] = [
  // ── TRIAGE ──────────────────────────────────────────────────────────────
  {
    id: 1n,
    en: "What is your main symptom today?",
    hi: "आज आपका मुख्य लक्षण क्या है?",
    mr: "आज तुमचे मुख्य लक्षण काय आहे?",
    type: "choice",
    options: [
      {
        value: "pain",
        en: "Abdominal pain or cramps",
        hi: "पेट में दर्द या ऐंठन",
        mr: "पोटात दुखणे किंवा पेटके",
      },
      {
        value: "swallow",
        en: "Difficulty swallowing",
        hi: "निगलने में कठिनाई",
        mr: "गिळण्यास त्रास",
      },
      {
        value: "heartburn",
        en: "Heartburn / acid reflux",
        hi: "सीने में जलन / एसिड रिफ्लक्स",
        mr: "छातीत जळजळ / आम्ल ओहोटी",
      },
      {
        value: "nausea",
        en: "Nausea or vomiting",
        hi: "मतली या उल्टी",
        mr: "मळमळ किंवा उलटी",
      },
      {
        value: "diarrhea",
        en: "Diarrhea (loose stools)",
        hi: "दस्त (पतले मल)",
        mr: "जुलाब (पातळ शौच)",
      },
      { value: "constipation", en: "Constipation", hi: "कब्ज", mr: "बद्धकोष्ठता" },
      {
        value: "bleeding",
        en: "Blood in stool / rectal bleeding",
        hi: "मल में खून / मलाशय से रक्तस्राव",
        mr: "शौचात रक्त / गुदाशयातून रक्तस्राव",
      },
      {
        value: "jaundice",
        en: "Yellow skin or eyes (jaundice)",
        hi: "पीली त्वचा या आँखें (पीलिया)",
        mr: "पिवळी त्वचा किंवा डोळे (कावीळ)",
      },
      {
        value: "other",
        en: "Other / bloating / gas",
        hi: "अन्य / पेट फूलना / गैस",
        mr: "इतर / पोट फुगणे / वायू",
      },
    ],
    nextMap: {
      pain: 10n,
      swallow: 20n,
      heartburn: 26n,
      nausea: 31n,
      diarrhea: 36n,
      constipation: 43n,
      bleeding: 48n,
      jaundice: 53n,
      other: 60n,
    },
    branch: "triage",
  },

  // ── BRANCH A: ABDOMINAL PAIN (Q10–Q14) ──────────────────────────────────
  {
    id: 10n,
    en: "Where is the pain located?",
    hi: "दर्द कहाँ है?",
    mr: "दुखणे कुठे आहे?",
    type: "choice",
    options: [
      {
        value: "upper",
        en: "Upper abdomen (epigastric)",
        hi: "ऊपरी पेट (एपीगैस्ट्रिक)",
        mr: "वरचे पोट (एपिगॅस्ट्रिक)",
      },
      { value: "lower", en: "Lower abdomen", hi: "निचला पेट", mr: "खालचे पोट" },
      {
        value: "right",
        en: "Right side (flank / RUQ)",
        hi: "दाहिनी ओर",
        mr: "उजवी बाजू",
      },
      {
        value: "left",
        en: "Left side (flank / LUQ)",
        hi: "बाईं ओर",
        mr: "डावी बाजू",
      },
      {
        value: "central",
        en: "Central / around the navel",
        hi: "मध्य / नाभि के आसपास",
        mr: "मध्यभागी / नाभीभोवती",
      },
      { value: "all", en: "All over / diffuse", hi: "पूरे पेट में", mr: "सर्वत्र" },
    ],
    nextMap: {
      upper: 11n,
      lower: 11n,
      right: 11n,
      left: 11n,
      central: 11n,
      all: 11n,
    },
    branch: "abdominal-pain",
  },
  {
    id: 11n,
    en: "How would you describe the pain?",
    hi: "दर्द को आप कैसे बताएंगे?",
    mr: "दुखणे कसे आहे?",
    type: "choice",
    options: [
      {
        value: "burning",
        en: "Burning / gnawing",
        hi: "जलन / चुभन",
        mr: "जळजळ / चुरचुरणे",
      },
      {
        value: "cramping",
        en: "Cramping / colicky",
        hi: "ऐंठन / मरोड़",
        mr: "पेटके / मरोड",
      },
      {
        value: "dull",
        en: "Dull / aching",
        hi: "हल्का / दर्दनाक",
        mr: "मंद / ठणका",
      },
      {
        value: "sharp",
        en: "Sharp / stabbing",
        hi: "तेज / चाकू जैसा",
        mr: "तीव्र / सुरीसारखे",
      },
    ],
    nextMap: { burning: 12n, cramping: 12n, dull: 12n, sharp: 12n },
    branch: "abdominal-pain",
  },
  {
    id: 12n,
    en: "Does the pain get worse after eating?",
    hi: "क्या खाने के बाद दर्द बढ़ता है?",
    mr: "जेवणानंतर दुखणे वाढते का?",
    type: "yesno",
    nextMap: { yes: 13n, no: 13n },
    branch: "abdominal-pain",
  },
  {
    id: 13n,
    en: "Does the pain spread to your back or shoulder?",
    hi: "क्या दर्द पीठ या कंधे तक फैलता है?",
    mr: "दुखणे पाठीवर किंवा खांद्यावर पसरते का?",
    type: "yesno",
    nextMap: { yes: 14n, no: 14n },
    branch: "abdominal-pain",
  },
  {
    id: 14n,
    en: "Rate the severity of your pain right now (1 = mild, 10 = worst imaginable)",
    hi: "अभी दर्द की तीव्रता को 1-10 पर रेट करें (1 = हल्का, 10 = असहनीय)",
    mr: "आत्ता दुखण्याची तीव्रता 1-10 वर रेट करा (1 = सौम्य, 10 = असह्य)",
    type: "scale",
    nextMap: {},
    branch: "abdominal-pain",
    // scale questions call submitAnswer with the number string; we route in component
  },

  // ── BRANCH B: DYSPHAGIA / OESOPHAGEAL (Q20–Q25) ──────────────────────────
  {
    id: 20n,
    en: "Is it harder to swallow solids, liquids, or both?",
    hi: "क्या ठोस, तरल या दोनों निगलने में कठिनाई है?",
    mr: "घन, द्रव किंवा दोन्ही गिळण्यास त्रास होतो का?",
    type: "choice",
    options: [
      { value: "solids", en: "Solids only", hi: "केवल ठोस", mr: "फक्त घन" },
      { value: "liquids", en: "Liquids only", hi: "केवल तरल", mr: "फक्त द्रव" },
      { value: "both", en: "Both solids and liquids", hi: "दोनों", mr: "दोन्ही" },
    ],
    nextMap: { solids: 21n, liquids: 21n, both: 21n },
    branch: "dysphagia",
  },
  {
    id: 21n,
    en: "Is it getting progressively worse over time?",
    hi: "क्या यह समय के साथ बदतर होता जा रहा है?",
    mr: "कालांतराने हे अधिकाधिक वाईट होत आहे का?",
    type: "yesno",
    nextMap: { yes: 22n, no: 22n },
    branch: "dysphagia",
  },
  {
    id: 22n,
    en: "Do you feel pain when swallowing (odynophagia)?",
    hi: "क्या निगलते समय दर्द होता है?",
    mr: "गिळताना दुखते का?",
    type: "yesno",
    nextMap: { yes: 23n, no: 23n },
    branch: "dysphagia",
  },
  {
    id: 23n,
    en: "Do you feel food sticking or getting stuck in your chest or throat?",
    hi: "क्या आपको लगता है कि खाना छाती या गले में अटकता है?",
    mr: "अन्न छातीत किंवा घशात अडकल्यासारखे वाटते का?",
    type: "yesno",
    nextMap: { yes: 24n, no: 24n },
    branch: "dysphagia",
  },
  {
    id: 24n,
    en: "Have you been regurgitating undigested food?",
    hi: "क्या बिना पचे भोजन वापस आ रहा है?",
    mr: "न पचलेले अन्न परत येत आहे का?",
    type: "yesno",
    nextMap: { yes: 25n, no: 80n },
    branch: "dysphagia",
  },
  {
    id: 25n,
    en: "Does regurgitation occur immediately after eating or hours later?",
    hi: "क्या खाने के तुरंत बाद या घंटों बाद उल्टी होती है?",
    mr: "जेवणानंतर लगेच की तासांनी परत येते?",
    type: "choice",
    options: [
      {
        value: "immediate",
        en: "Immediately after eating",
        hi: "खाने के तुरंत बाद",
        mr: "जेवणानंतर लगेच",
      },
      {
        value: "hours",
        en: "Hours after eating",
        hi: "खाने के घंटों बाद",
        mr: "जेवणानंतर तासांनी",
      },
    ],
    nextMap: { immediate: 80n, hours: 80n },
    branch: "dysphagia",
  },

  // ── BRANCH C: HEARTBURN / GERD (Q26–Q30) ─────────────────────────────────
  {
    id: 26n,
    en: "How often do you experience heartburn or chest burning?",
    hi: "आपको सीने में जलन कितनी बार होती है?",
    mr: "छातीत जळजळ किती वेळा होते?",
    type: "choice",
    options: [
      {
        value: "rare",
        en: "Rarely (less than once a week)",
        hi: "कभी-कभी (सप्ताह में एक बार से कम)",
        mr: "क्वचित (आठवड्यातून एकापेक्षा कमी)",
      },
      {
        value: "weekly",
        en: "1–2 times per week",
        hi: "सप्ताह में 1-2 बार",
        mr: "आठवड्यातून 1-2 वेळा",
      },
      {
        value: "frequent",
        en: "3 or more times per week",
        hi: "सप्ताह में 3 या अधिक बार",
        mr: "आठवड्यातून 3 किंवा जास्त वेळा",
      },
      { value: "daily", en: "Daily", hi: "प्रतिदिन", mr: "दररोज" },
    ],
    nextMap: { rare: 27n, weekly: 27n, frequent: 27n, daily: 27n },
    branch: "heartburn",
  },
  {
    id: 27n,
    en: "Does stomach acid or food come back up into your throat or mouth?",
    hi: "क्या पेट का एसिड या खाना गले या मुँह में आता है?",
    mr: "पोटातील आम्ल किंवा अन्न घशात किंवा तोंडात येते का?",
    type: "yesno",
    nextMap: { yes: 28n, no: 28n },
    branch: "heartburn",
  },
  {
    id: 28n,
    en: "Does the burning wake you up from sleep?",
    hi: "क्या जलन से आप नींद से जाग जाते हैं?",
    mr: "जळजळीमुळे तुम्हाला झोपेतून जाग येते का?",
    type: "yesno",
    nextMap: { yes: 29n, no: 29n },
    branch: "heartburn",
  },
  {
    id: 29n,
    en: "Does it worsen when lying flat, bending over, or after a large meal?",
    hi: "क्या लेटने, झुकने या भारी भोजन के बाद यह बदतर होता है?",
    mr: "सपाट झोपताना, वाकताना किंवा जड जेवणानंतर ते वाढते का?",
    type: "yesno",
    nextMap: { yes: 30n, no: 30n },
    branch: "heartburn",
  },
  {
    id: 30n,
    en: "Have you tried antacids or acid-reducing medications? Did they help?",
    hi: "क्या आपने एंटासिड या एसिड कम करने वाली दवाएं लीं? क्या उनसे फायदा हुआ?",
    mr: "तुम्ही अँटासिड किंवा आम्ल कमी करणारी औषधे घेतली का? त्याने फरक पडला का?",
    type: "choice",
    options: [
      {
        value: "yes_helped",
        en: "Yes, they helped",
        hi: "हाँ, फायदा हुआ",
        mr: "होय, फरक पडला",
      },
      {
        value: "yes_no_help",
        en: "Yes, but they did not help",
        hi: "हाँ, लेकिन फायदा नहीं",
        mr: "होय, पण फरक नाही",
      },
      {
        value: "not_tried",
        en: "I have not tried them",
        hi: "मैंने कोशिश नहीं की",
        mr: "मी प्रयत्न केला नाही",
      },
    ],
    nextMap: { yes_helped: 80n, yes_no_help: 80n, not_tried: 80n },
    branch: "heartburn",
  },

  // ── BRANCH D: NAUSEA / VOMITING (Q31–Q35) ────────────────────────────────
  {
    id: 31n,
    en: "How often are you vomiting?",
    hi: "आप कितनी बार उल्टी कर रहे हैं?",
    mr: "तुम्हाला किती वेळा उलटी होते?",
    type: "choice",
    options: [
      { value: "rare", en: "Rarely / occasional", hi: "कभी-कभी", mr: "क्वचित" },
      {
        value: "daily",
        en: "Once daily",
        hi: "दिन में एक बार",
        mr: "दिवसातून एकदा",
      },
      {
        value: "multiple",
        en: "Multiple times per day",
        hi: "दिन में कई बार",
        mr: "दिवसातून अनेक वेळा",
      },
      {
        value: "nausea_only",
        en: "Nausea only, no vomiting",
        hi: "केवल मतली, उल्टी नहीं",
        mr: "फक्त मळमळ, उलटी नाही",
      },
    ],
    nextMap: { rare: 32n, daily: 32n, multiple: 32n, nausea_only: 32n },
    branch: "nausea",
  },
  {
    id: 32n,
    en: "Does the vomit contain blood or look like dark coffee grounds?",
    hi: "क्या उल्टी में खून है या यह काफी के मैदान जैसी दिखती है?",
    mr: "उलटीत रक्त आहे का किंवा ती गडद कॉफी ग्राउंडसारखी दिसते का?",
    type: "yesno",
    nextMap: { yes: 33n, no: 33n },
    branch: "nausea",
  },
  {
    id: 33n,
    en: "Does vomiting occur shortly after eating?",
    hi: "क्या खाने के तुरंत बाद उल्टी होती है?",
    mr: "जेवणानंतर लगेच उलटी होते का?",
    type: "yesno",
    nextMap: { yes: 34n, no: 34n },
    branch: "nausea",
  },
  {
    id: 34n,
    en: "Is the nausea or vomiting associated with abdominal pain?",
    hi: "क्या मतली या उल्टी पेट दर्द के साथ है?",
    mr: "मळमळ किंवा उलटी पोटदुखीसोबत आहे का?",
    type: "yesno",
    nextMap: { yes: 35n, no: 80n },
    branch: "nausea",
  },
  {
    id: 35n,
    en: "Does the pain ease after vomiting?",
    hi: "क्या उल्टी के बाद दर्द कम होता है?",
    mr: "उलटीनंतर दुखणे कमी होते का?",
    type: "yesno",
    nextMap: { yes: 80n, no: 80n },
    branch: "nausea",
  },

  // ── BRANCH E: DIARRHEA (Q36–Q42) ─────────────────────────────────────────
  {
    id: 36n,
    en: "How many times per day do you have loose or watery stools?",
    hi: "प्रतिदिन कितनी बार पतले या पानी जैसे मल होते हैं?",
    mr: "दिवसातून किती वेळा पातळ किंवा पाण्यासारखा शौच होतो?",
    type: "choice",
    options: [
      { value: "two_three", en: "2–3 times", hi: "2-3 बार", mr: "2-3 वेळा" },
      { value: "four_six", en: "4–6 times", hi: "4-6 बार", mr: "4-6 वेळा" },
      {
        value: "more",
        en: "More than 6 times",
        hi: "6 बार से अधिक",
        mr: "6 पेक्षा जास्त वेळा",
      },
    ],
    nextMap: { two_three: 37n, four_six: 37n, more: 37n },
    branch: "diarrhea",
  },
  {
    id: 37n,
    en: "Is there blood in your stool?",
    hi: "क्या मल में खून है?",
    mr: "शौचात रक्त आहे का?",
    type: "yesno",
    nextMap: { yes: 38n, no: 38n },
    branch: "diarrhea",
  },
  {
    id: 38n,
    en: "Is there mucus in your stool?",
    hi: "क्या मल में बलगम है?",
    mr: "शौचात श्लेष्मा आहे का?",
    type: "yesno",
    nextMap: { yes: 39n, no: 39n },
    branch: "diarrhea",
  },
  {
    id: 39n,
    en: "Does the diarrhea wake you up at night?",
    hi: "क्या रात में दस्त से नींद खुल जाती है?",
    mr: "रात्री जुलाबामुळे जाग येते का?",
    type: "yesno",
    nextMap: { yes: 40n, no: 40n },
    branch: "diarrhea",
  },
  {
    id: 40n,
    en: "Is there urgency — do you need to rush to the toilet?",
    hi: "क्या आपको तुरंत शौचालय जाने की जरूरत महसूस होती है?",
    mr: "लगेच शौचालयात जाण्याची घाई लागते का?",
    type: "yesno",
    nextMap: { yes: 41n, no: 41n },
    branch: "diarrhea",
  },
  {
    id: 41n,
    en: "How long have you had diarrhea?",
    hi: "आपको कितने समय से दस्त है?",
    mr: "किती दिवसांपासून जुलाब आहे?",
    type: "choice",
    options: [
      {
        value: "less_two_weeks",
        en: "Less than 2 weeks (acute)",
        hi: "2 सप्ताह से कम (तीव्र)",
        mr: "2 आठवड्यांपेक्षा कमी (तीव्र)",
      },
      {
        value: "two_to_four",
        en: "2–4 weeks",
        hi: "2–4 सप्ताह",
        mr: "2–4 आठवडे",
      },
      {
        value: "more_four",
        en: "More than 4 weeks (chronic)",
        hi: "4 सप्ताह से अधिक (दीर्घकालिक)",
        mr: "4 आठवड्यांपेक्षा जास्त (जुनाट)",
      },
    ],
    nextMap: { less_two_weeks: 42n, two_to_four: 42n, more_four: 42n },
    branch: "diarrhea",
  },
  {
    id: 42n,
    en: "Have you recently travelled abroad or had food that could have been contaminated?",
    hi: "क्या आपने हाल ही में विदेश यात्रा की है या दूषित भोजन खाया है?",
    mr: "अलीकडे परदेश प्रवास केला का किंवा दूषित अन्न खाल्ले का?",
    type: "yesno",
    nextMap: { yes: 80n, no: 80n },
    branch: "diarrhea",
  },

  // ── BRANCH F: CONSTIPATION (Q43–Q47) ─────────────────────────────────────
  {
    id: 43n,
    en: "How many times per week do you normally open your bowels?",
    hi: "आप सामान्यतः प्रति सप्ताह कितनी बार मलत्याग करते हैं?",
    mr: "तुम्ही सहसा आठवड्यातून किती वेळा शौचास जाता?",
    type: "choice",
    options: [
      {
        value: "three_plus",
        en: "3 or more times",
        hi: "3 या अधिक बार",
        mr: "3 किंवा जास्त वेळा",
      },
      { value: "one_two", en: "1–2 times", hi: "1-2 बार", mr: "1-2 वेळा" },
      {
        value: "less_one",
        en: "Less than once a week",
        hi: "सप्ताह में एक बार से कम",
        mr: "आठवड्यातून एकापेक्षा कमी",
      },
    ],
    nextMap: { three_plus: 44n, one_two: 44n, less_one: 44n },
    branch: "constipation",
  },
  {
    id: 44n,
    en: "Do you have to strain hard to pass stools?",
    hi: "क्या मल त्यागने के लिए आपको काफी जोर लगाना पड़ता है?",
    mr: "शौच करण्यासाठी खूप जोर द्यावा लागतो का?",
    type: "yesno",
    nextMap: { yes: 45n, no: 45n },
    branch: "constipation",
  },
  {
    id: 45n,
    en: "Do you feel like your bowels are not completely empty after going to the toilet?",
    hi: "क्या शौचालय जाने के बाद भी लगता है कि पेट पूरी तरह साफ नहीं हुआ?",
    mr: "शौचालयातून आल्यावरही पोट पूर्णपणे साफ झाले नाही असे वाटते का?",
    type: "yesno",
    nextMap: { yes: 46n, no: 46n },
    branch: "constipation",
  },
  {
    id: 46n,
    en: "Has the shape or size of your stool changed recently (e.g., narrow/ribbon-like stools)?",
    hi: "क्या हाल ही में मल का आकार या रूप बदल गया है (जैसे पतला/रिबन जैसा)?",
    mr: "अलीकडे शौचाचा आकार किंवा रूप बदलला आहे का (उदा. पातळ/रिबनसारखा)?",
    type: "yesno",
    nextMap: { yes: 47n, no: 80n },
    branch: "constipation",
  },
  {
    id: 47n,
    en: "Is the constipation alternating with episodes of diarrhea?",
    hi: "क्या कब्ज और दस्त बारी-बारी आते हैं?",
    mr: "बद्धकोष्ठता आणि जुलाब आळीपाळीने होतात का?",
    type: "yesno",
    nextMap: { yes: 80n, no: 80n },
    branch: "constipation",
  },

  // ── BRANCH G: RECTAL BLEEDING (Q48–Q52) ──────────────────────────────────
  {
    id: 48n,
    en: "What does the blood look like?",
    hi: "खून कैसा दिखता है?",
    mr: "रक्त कसे दिसते?",
    type: "choice",
    options: [
      {
        value: "bright_red",
        en: "Bright red blood",
        hi: "चमकदार लाल खून",
        mr: "चमकदार लाल रक्त",
      },
      {
        value: "dark_maroon",
        en: "Dark red / maroon blood",
        hi: "गहरा लाल / मैरून खून",
        mr: "गडद लाल / मरून रक्त",
      },
      {
        value: "black_tar",
        en: "Black / tar-like stools (melaena)",
        hi: "काला / तारकोल जैसा मल",
        mr: "काळा / डांबरासारखा शौच",
      },
      {
        value: "on_paper",
        en: "Only noticed on toilet paper",
        hi: "केवल टॉयलेट पेपर पर",
        mr: "फक्त टॉयलेट पेपरवर",
      },
    ],
    nextMap: {
      bright_red: 49n,
      dark_maroon: 49n,
      black_tar: 49n,
      on_paper: 49n,
    },
    branch: "bleeding",
  },
  {
    id: 49n,
    en: "Is the blood mixed in with the stool or on the surface only?",
    hi: "क्या खून मल के साथ मिला है या केवल ऊपर है?",
    mr: "रक्त शौचात मिसळलेले आहे का फक्त वर आहे?",
    type: "choice",
    options: [
      {
        value: "mixed",
        en: "Mixed in with the stool",
        hi: "मल के साथ मिला",
        mr: "शौचात मिसळलेले",
      },
      {
        value: "surface",
        en: "On the surface / coating",
        hi: "केवल ऊपर",
        mr: "फक्त वर",
      },
      {
        value: "dripping",
        en: "Dripping into the toilet",
        hi: "शौचालय में टपकता",
        mr: "शौचालयात टपकणारे",
      },
    ],
    nextMap: { mixed: 50n, surface: 50n, dripping: 50n },
    branch: "bleeding",
  },
  {
    id: 50n,
    en: "Is there pain associated with the bleeding?",
    hi: "क्या रक्तस्राव के साथ दर्द है?",
    mr: "रक्तस्रावासोबत दुखणे आहे का?",
    type: "yesno",
    nextMap: { yes: 51n, no: 51n },
    branch: "bleeding",
  },
  {
    id: 51n,
    en: "How long have you been noticing blood?",
    hi: "आपको कितने समय से खून दिख रहा है?",
    mr: "किती दिवसांपासून रक्त दिसत आहे?",
    type: "choice",
    options: [
      {
        value: "days",
        en: "A few days",
        hi: "कुछ दिनों से",
        mr: "काही दिवसांपासून",
      },
      {
        value: "weeks",
        en: "A few weeks",
        hi: "कुछ हफ्तों से",
        mr: "काही आठवड्यांपासून",
      },
      {
        value: "months",
        en: "Several months",
        hi: "कई महीनों से",
        mr: "अनेक महिन्यांपासून",
      },
    ],
    nextMap: { days: 52n, weeks: 52n, months: 52n },
    branch: "bleeding",
  },
  {
    id: 52n,
    en: "Have you ever had piles (haemorrhoids), polyps, or a colonoscopy before?",
    hi: "क्या आपको पहले बवासीर, पॉलीप्स हुए हैं या कोलोनोस्कोपी हुई है?",
    mr: "तुम्हाला आधी मूळव्याध, पॉलिप्स झाले आहेत का किंवा कोलोनोस्कोपी झाली आहे का?",
    type: "yesno",
    nextMap: { yes: 80n, no: 80n },
    branch: "bleeding",
  },

  // ── BRANCH H: JAUNDICE (Q53–Q57) ─────────────────────────────────────────
  {
    id: 53n,
    en: "Is your urine dark (like tea or cola)?",
    hi: "क्या आपका पेशाब गहरे रंग का है (जैसे चाय या कोला)?",
    mr: "तुमचे लघवी गडद रंगाचे आहे (चहा किंवा कोल्डड्रिंकसारखे)?",
    type: "yesno",
    nextMap: { yes: 54n, no: 54n },
    branch: "jaundice",
  },
  {
    id: 54n,
    en: "Are your stools pale, clay-coloured, or white?",
    hi: "क्या आपका मल पीला, मिट्टी के रंग का या सफेद है?",
    mr: "तुमचा शौच फिकट, मातीच्या रंगाचा किंवा पांढरा आहे का?",
    type: "yesno",
    nextMap: { yes: 55n, no: 55n },
    branch: "jaundice",
  },
  {
    id: 55n,
    en: "Do you have itching all over your body?",
    hi: "क्या पूरे शरीर में खुजली होती है?",
    mr: "संपूर्ण शरीरावर खाज येते का?",
    type: "yesno",
    nextMap: { yes: 56n, no: 56n },
    branch: "jaundice",
  },
  {
    id: 56n,
    en: "Do you have pain in your right upper abdomen or under the right rib cage?",
    hi: "क्या दाहिने ऊपरी पेट में या दाहिनी पसलियों के नीचे दर्द है?",
    mr: "उजव्या वरच्या पोटात किंवा उजव्या बरगड्यांखाली दुखते का?",
    type: "yesno",
    nextMap: { yes: 57n, no: 80n },
    branch: "jaundice",
  },
  {
    id: 57n,
    en: "Does the pain spread to your right shoulder or back?",
    hi: "क्या दर्द दाहिने कंधे या पीठ तक फैलता है?",
    mr: "दुखणे उजव्या खांद्यावर किंवा पाठीवर पसरते का?",
    type: "yesno",
    nextMap: { yes: 80n, no: 80n },
    branch: "jaundice",
  },

  // ── BRANCH I: OTHER / FUNCTIONAL / BLOATING (Q60–Q64) ────────────────────
  {
    id: 60n,
    en: "Do you feel bloated or uncomfortably full after small meals?",
    hi: "क्या थोड़ा खाने के बाद भी पेट फूला हुआ या बहुत भरा लगता है?",
    mr: "थोडे जेवल्यावरही पोट फुगलेले किंवा खूप भरलेले वाटते का?",
    type: "yesno",
    nextMap: { yes: 61n, no: 61n },
    branch: "functional",
  },
  {
    id: 61n,
    en: "Do you have excessive gas or belching?",
    hi: "क्या अत्यधिक गैस या डकारें आती हैं?",
    mr: "जास्त वायू किंवा ढेकरा येतात का?",
    type: "yesno",
    nextMap: { yes: 62n, no: 62n },
    branch: "functional",
  },
  {
    id: 62n,
    en: "Do your symptoms improve after passing wind or having a bowel movement?",
    hi: "क्या गैस निकलने या मलत्याग के बाद लक्षण बेहतर होते हैं?",
    mr: "वायू सुटल्यावर किंवा शौचानंतर लक्षणे कमी होतात का?",
    type: "yesno",
    nextMap: { yes: 63n, no: 63n },
    branch: "functional",
  },
  {
    id: 63n,
    en: "Do stress or anxiety tend to worsen your symptoms?",
    hi: "क्या तनाव या चिंता से लक्षण बढ़ते हैं?",
    mr: "तणाव किंवा चिंतेमुळे लक्षणे वाढतात का?",
    type: "yesno",
    nextMap: { yes: 64n, no: 64n },
    branch: "functional",
  },
  {
    id: 64n,
    en: "How much do your symptoms affect your daily activities? (1 = not at all, 10 = cannot function)",
    hi: "आपके लक्षण आपकी दैनिक गतिविधियों को कितना प्रभावित करते हैं? (1 = बिल्कुल नहीं, 10 = बिल्कुल नहीं कर सकता)",
    mr: "तुमची लक्षणे तुमच्या दैनंदिन कामांवर किती परिणाम करतात? (1 = अजिबात नाही, 10 = काही करता येत नाही)",
    type: "scale",
    nextMap: {},
    branch: "functional",
  },

  // ── RED FLAGS / SYSTEMIC REVIEW (Q80–Q87) ─────────────────────────────────
  // All branches lead here
  {
    id: 80n,
    en: "Have you lost weight unintentionally in the last 3 months?",
    hi: "क्या पिछले 3 महीनों में अनजाने में आपका वजन कम हुआ है?",
    mr: "गेल्या 3 महिन्यांत अनावधानाने वजन कमी झाले का?",
    type: "yesno",
    nextMap: { yes: 81n, no: 81n },
    branch: "red-flags",
  },
  {
    id: 81n,
    en: "Have you had fever or chills?",
    hi: "क्या आपको बुखार या ठंड लगी है?",
    mr: "ताप किंवा थंडी वाजणे झाले का?",
    type: "yesno",
    nextMap: { yes: 82n, no: 82n },
    branch: "red-flags",
  },
  {
    id: 82n,
    en: "Have you noticed any yellowing of your skin or eyes (jaundice)?",
    hi: "क्या आपने त्वचा या आँखों में पीलापन देखा है (पीलिया)?",
    mr: "त्वचेवर किंवा डोळ्यांत पिवळसरपणा दिसला का (कावीळ)?",
    type: "yesno",
    nextMap: { yes: 83n, no: 83n },
    branch: "red-flags",
  },
  {
    id: 83n,
    en: "Have you lost your appetite significantly?",
    hi: "क्या आपकी भूख काफी कम हो गई है?",
    mr: "भूक लक्षणीयरीत्या कमी झाली आहे का?",
    type: "yesno",
    nextMap: { yes: 84n, no: 84n },
    branch: "red-flags",
  },
  {
    id: 84n,
    en: "Do you feel unusually tired or fatigued most days?",
    hi: "क्या आप अधिकतर दिनों में असामान्य रूप से थका हुआ महसूस करते हैं?",
    mr: "बहुतेक दिवस असामान्यपणे थकलेले किंवा शिणलेले वाटते का?",
    type: "yesno",
    nextMap: { yes: 85n, no: 85n },
    branch: "red-flags",
  },
  {
    id: 85n,
    en: "Is there a family history of bowel cancer, stomach cancer, inflammatory bowel disease, or liver disease?",
    hi: "क्या परिवार में आंत्र कैंसर, पेट का कैंसर, आईबीडी या लिवर रोग का इतिहास है?",
    mr: "कुटुंबात आतड्याचा कर्करोग, पोटाचा कर्करोग, IBD किंवा यकृताच्या आजाराचा इतिहास आहे का?",
    type: "yesno",
    nextMap: { yes: 86n, no: 86n },
    branch: "red-flags",
  },
  {
    id: 86n,
    en: "Are you regularly taking any of these: aspirin, ibuprofen, naproxen, or other anti-inflammatory painkillers (NSAIDs)?",
    hi: "क्या आप नियमित रूप से एस्पिरिन, इबुप्रोफेन, नेप्रोक्सेन या अन्य सूजन-रोधी दर्दनाशक (NSAIDs) लेते हैं?",
    mr: "तुम्ही नियमितपणे ऍस्पिरिन, इबुप्रोफेन, नेप्रोक्सेन किंवा इतर दाहविरोधी वेदनाशामक (NSAIDs) घेता का?",
    type: "yesno",
    nextMap: { yes: 87n, no: 87n },
    branch: "red-flags",
  },
  {
    id: 87n,
    en: "How long have your current symptoms been present?",
    hi: "आपके वर्तमान लक्षण कितने समय से हैं?",
    mr: "तुमची सध्याची लक्षणे किती दिवसांपासून आहेत?",
    type: "choice",
    options: [
      {
        value: "days",
        en: "A few days",
        hi: "कुछ दिनों से",
        mr: "काही दिवसांपासून",
      },
      { value: "weeks", en: "1–4 weeks", hi: "1-4 सप्ताह", mr: "1-4 आठवडे" },
      {
        value: "one_three_m",
        en: "1–3 months",
        hi: "1-3 महीने",
        mr: "1-3 महिने",
      },
      {
        value: "three_plus",
        en: "More than 3 months",
        hi: "3 महीने से अधिक",
        mr: "3 महिन्यांपेक्षा जास्त",
      },
      {
        value: "years",
        en: "More than a year",
        hi: "एक वर्ष से अधिक",
        mr: "एक वर्षापेक्षा जास्त",
      },
    ],
    // No nextMap = terminal → session completes
    branch: "red-flags",
  },
];

export const QUESTION_MAP = new Map<bigint, Question>(
  QUESTIONS.map((q) => [q.id, q]),
);

export const TOTAL_QUESTIONS = QUESTIONS.length;

// After a "scale" question, route to the red-flag section
export const SCALE_NEXT: Record<string, bigint> = {
  "14": 80n, // pain severity -> red flags
  "64": 80n, // functional impact -> red flags
};
